name: 💄 Linting
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: 🔀 Checking out Repo
        uses: actions/checkout@v4

      - name: ⬇️ Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 📦 Installing Dependencies
        run: yarn install && ls

      - name: ⌛️ Running ESLint
        run: |
          cd packages/custoplayer
          yarn lint
