name: 📊 Tests
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔀 Checking out Repo
        uses: actions/checkout@v3

      - name: ⬇️ Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 📦 Installing Other Dependencies
        run: yarn install && ls

      - name: ⌛️ Running Cypress Component Tests
        uses: cypress-io/github-action@v5.7.1
        with:
          build: yarn build
          component: true
          config-file: cypress.config.ts
          working-directory: packages/custoplayer

      - name: ⌛️ Running Cypress E2E Tests
        uses: cypress-io/github-action@v5.7.1
        with:

          browser: chrome
          config-file: cypress.config.ts
          install: false
          start: yarn dev
          wait-on: 'http://localhost:3000'
          working-directory: packages/custoplayer

      - name: 📝 Create coverage xml file
        run: cd packages/custoplayer/ &&  npx nyc report --reporter=clover

      - name: ⬆️ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
