name: 📊 Tests
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔀 Checking out Repo
        uses: actions/checkout@v3

      - name: ⬇️ Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 📦 Installing Other Dependencies
        run: yarn install && ls

      - name: ⌛️ Running Cypress Component Tests
        uses: cypress-io/github-action@v5.3.0
        with:
          config-file: cypress.config.js
          working-directory: packages/custoplayer
          component: true
          build: yarn build

      - name: ⌛️ Running Cypress E2E Tests
        uses: cypress-io/github-action@v5.3.0
        with:
          wait-on: 'http://localhost:3000'
          browser: chrome
          config-file: cypress.config.js
          working-directory: packages/custoplayer
          build: yarn build
          start: yarn dev
          install: false

      - name: ⬆️ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
